export class ApiEntreprise {
  etablissement: {
    "siren": string,
    "nic": string,
    "siret": string,
    "statutDiffusionEtablissement": string,
    "dateCreationEtablissement": string,
    "trancheEffectifsEtablissement": string,
    "anneeEffectifsEtablissement": string,
    "activitePrincipaleRegistreMetiersEtablissement": string,
    "dateDernierTraitementEtablissement": string,
    "etablissementSiege": boolean,
    "nombrePeriodesEtablissement": number,
    "uniteLegale": {
      "etatAdministratifUniteLegale": string,
      "statutDiffusionUniteLegale": string,
      "dateCreationUniteLegale": string,
      "categorieJuridiqueUniteLegale": string,
      "denominationUniteLegale": string,
      "sigleUniteLegale": string,
      "denominationUsuelle1UniteLegale": string,
      "denominationUsuelle2UniteLegale": string,
      "denominationUsuelle3UniteLegale": string,
      "sexeUniteLegale": string,
      "nomUniteLegale": string,
      "nomUsageUniteLegale": string,
      "prenom1UniteLegale": string,
      "prenom2UniteLegale": string,
      "prenom3UniteLegale": string,
      "prenom4UniteLegale": string,
      "prenomUsuelUniteLegale": string,
      "pseudonymeUniteLegale": string,
      "activitePrincipaleUniteLegale": string,
      "nomenclatureActivitePrincipaleUniteLegale": string,
      "identifiantAssociationUniteLegale": string,
      "economieSocialeSolidaireUniteLegale": string,
      "societeMissionUniteLegale": string,
      "caractereEmployeurUniteLegale": string,
      "trancheEffectifsUniteLegale": string,
      "anneeEffectifsUniteLegale": string,
      "nicSiegeUniteLegale": string,
      "dateDernierTraitementUniteLegale": string,
      "categorieEntreprise": string,
      "anneeCategorieEntreprise": string
    },
    "adresseEtablissement": {
      "complementAdresseEtablissement": string,
      "numeroVoieEtablissement": string,
      "indiceRepetitionEtablissement": string,
      "typeVoieEtablissement": string,
      "libelleVoieEtablissement": string,
      "codePostalEtablissement": string,
      "libelleCommuneEtablissement": string,
      "libelleCommuneEtrangerEtablissement": string,
      "distributionSpecialeEtablissement": string,
      "codeCommuneEtablissement": string,
      "codeCedexEtablissement": string,
      "libelleCedexEtablissement": string,
      "codePaysEtrangerEtablissement": string,
      "libellePaysEtrangerEtablissement": string
    },
    "adresse2Etablissement": {
      "complementAdresse2Etablissement": string,
      "numeroVoie2Etablissement": string,
      "indiceRepetition2Etablissement": string,
      "typeVoie2Etablissement": string,
      "libelleVoie2Etablissement": string,
      "codePostal2Etablissement": string,
      "libelleCommune2Etablissement": string,
      "libelleCommuneEtranger2Etablissement": string,
      "distributionSpeciale2Etablissement": string,
      "codeCommune2Etablissement": string,
      "codeCedex2Etablissement": string,
      "libelleCedex2Etablissement": string,
      "codePaysEtranger2Etablissement": string,
      "libellePaysEtranger2Etablissement": string
    },
    "periodesEtablissement": [
      {
        "dateFin": string,
        "dateDebut": string,
        "etatAdministratifEtablissement": string,
        "changementEtatAdministratifEtablissement": boolean,
        "enseigne1Etablissement": string,
        "enseigne2Etablissement": string,
        "enseigne3Etablissement": string,
        "changementEnseigneEtablissement": boolean,
        "denominationUsuelleEtablissement": string,
        "changementDenominationUsuelleEtablissement": boolean,
        "activitePrincipaleEtablissement": string,
        "nomenclatureActivitePrincipaleEtablissement": string,
        "changementActivitePrincipaleEtablissement": boolean,
        "caractereEmployeurEtablissement": string,
        "changementCaractereEmployeurEtablissement": boolean
      },
      {
        "dateFin": string,
        "dateDebut": string,
        "etatAdministratifEtablissement": string,
        "changementEtatAdministratifEtablissement": boolean,
        "enseigne1Etablissement": string,
        "enseigne2Etablissement": string,
        "enseigne3Etablissement": string,
        "changementEnseigneEtablissement": boolean,
        "denominationUsuelleEtablissement": string,
        "changementDenominationUsuelleEtablissement": boolean,
        "activitePrincipaleEtablissement": string,
        "nomenclatureActivitePrincipaleEtablissement": string,
        "changementActivitePrincipaleEtablissement": boolean,
        "caractereEmployeurEtablissement": string,
        "changementCaractereEmployeurEtablissement": boolean
      },
      {
        "dateFin": string,
        "dateDebut": string,
        "etatAdministratifEtablissement": string,
        "changementEtatAdministratifEtablissement": boolean,
        "enseigne1Etablissement": string,
        "enseigne2Etablissement": string,
        "enseigne3Etablissement": string,
        "changementEnseigneEtablissement": boolean,
        "denominationUsuelleEtablissement": string,
        "changementDenominationUsuelleEtablissement": boolean,
        "activitePrincipaleEtablissement": string,
        "nomenclatureActivitePrincipaleEtablissement": string,
        "changementActivitePrincipaleEtablissement": boolean,
        "caractereEmployeurEtablissement": string,
        "changementCaractereEmployeurEtablissement": boolean
      },
      {
        "dateFin": string,
        "dateDebut": string,
        "etatAdministratifEtablissement": string,
        "changementEtatAdministratifEtablissement": boolean,
        "enseigne1Etablissement": string,
        "enseigne2Etablissement": string,
        "enseigne3Etablissement": string,
        "changementEnseigneEtablissement": boolean,
        "denominationUsuelleEtablissement": string,
        "changementDenominationUsuelleEtablissement": boolean,
        "activitePrincipaleEtablissement": string,
        "nomenclatureActivitePrincipaleEtablissement": string,
        "changementActivitePrincipaleEtablissement": boolean,
        "caractereEmployeurEtablissement": string,
        "changementCaractereEmployeurEtablissement": boolean
      },
      {
        "dateFin": string,
        "dateDebut": string,
        "etatAdministratifEtablissement": string,
        "changementEtatAdministratifEtablissement": boolean,
        "enseigne1Etablissement": string,
        "enseigne2Etablissement": string,
        "enseigne3Etablissement": string,
        "changementEnseigneEtablissement": boolean,
        "denominationUsuelleEtablissement": string,
        "changementDenominationUsuelleEtablissement": boolean,
        "activitePrincipaleEtablissement": string,
        "nomenclatureActivitePrincipaleEtablissement": string,
        "changementActivitePrincipaleEtablissement": boolean,
        "caractereEmployeurEtablissement": string,
        "changementCaractereEmployeurEtablissement": boolean
      },
      {
        "dateFin": string,
        "dateDebut": string,
        "etatAdministratifEtablissement": string,
        "changementEtatAdministratifEtablissement": boolean,
        "enseigne1Etablissement": string,
        "enseigne2Etablissement": string,
        "enseigne3Etablissement": string,
        "changementEnseigneEtablissement": boolean,
        "denominationUsuelleEtablissement": string,
        "changementDenominationUsuelleEtablissement": boolean,
        "activitePrincipaleEtablissement": string,
        "nomenclatureActivitePrincipaleEtablissement": string,
        "changementActivitePrincipaleEtablissement": boolean,
        "caractereEmployeurEtablissement": string,
        "changementCaractereEmployeurEtablissement": boolean
      }
    ]
  }
}
